version: "2.4"
services:
  mockServer:
    image: mockserver/mockserver:mockserver-snapshot
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: config/initializerJson.json
    volumes:
      - type: bind
        source: ./mockserver/config
        target: /config
